export const orderData = [
  {
    key: "1",
    custID: "#1465",
    latestOrderDate: "03 April 2025, 09:57 PM",
    customerName: "Johnny Silverhand",
    deviceUse: "Counter 1",
    amount: "$233.25",
    customerStatus: "In Progress",
  },
  {
    key: "2",
    custID: "#1462",
    latestOrderDate: "03 April 2025, 10:14 PM",
    customerName: "Daniel Esperanzo Bravosica Jr.",
    deviceUse: "Counter 4",
    amount: "$118.36",
    customerStatus: "In Progress",
  },
  {
    key: "3",
    custID: "#1372",
    latestOrderDate: "03 April 2025, 09:32 PM",
    customerName: "Travis Tanner",
    deviceUse: "Counter 3",
    amount: "$64.35",
    customerStatus: "In Progress",
  },
  {
    key: "4",
    custID: "#1298",
    latestOrderDate: "03 April 2025, 09:18 PM",
    customerName: "Jessica Kang",
    deviceUse: "Counter 2",
    amount: "$79.67",
    customerStatus: "Ready for Pick Up",
  },
  {
    key: "5",
    custID: "#1264",
    latestOrderDate: "03 April 2025, 09:16 PM",
    customerName: "Monica Ngyuen",
    deviceUse: "Counter 4",
    amount: "$32.84",
    customerStatus: "Picked Up",
  },
];

export const orderData2 = [
  {
    key: "1",
    custID: "#1465",
    latestOrderDate: "03 April 2025, 09:57 PM",
    customerName: "Johnny Silverhand",
    deviceUse: "Counter 1",
    amount: "$233.25",
    customerStatus: "01",
  },
  {
    key: "2",
    custID: "#1462",
    latestOrderDate: "03 April 2025, 10:14 PM",
    customerName: "Daniel Esperanzo Bravosica Jr.",
    deviceUse: "Counter 4",
    amount: "$118.36",
    customerStatus: "01",
  },
  {
    key: "3",
    custID: "#1372",
    latestOrderDate: "03 April 2025, 09:32 PM",
    customerName: "Travis Tanner",
    deviceUse: "Counter 3",
    amount: "$64.35",
    customerStatus: "01",
  },
  {
    key: "4",
    custID: "#1298",
    latestOrderDate: "03 April 2025, 09:18 PM",
    customerName: "Jessica Kang",
    deviceUse: "Counter 2",
    amount: "$79.67",
    customerStatus: "01",
  },
  {
    key: "5",
    custID: "#1264",
    latestOrderDate: "03 April 2025, 09:16 PM",
    customerName: "Monica Ngyuen",
    deviceUse: "Counter 4",
    amount: "$32.84",
    customerStatus: "01",
  },
];

export const orderData3 = [
  {
    key: "1",
    custID: "#1465",
    latestOrderDate: "03 April 2025, 09:57 PM",
    customerName: "Johnny Silverhand",
    deviceUse: "Counter 1",
    amount: "$233.25",
    customerStatus: "Cancelled",
  },
  {
    key: "2",
    custID: "#1462",
    latestOrderDate: "03 April 2025, 10:14 PM",
    customerName: "Daniel Esperanzo Bravosica Jr.",
    deviceUse: "Counter 4",
    amount: "$118.36",
    customerStatus: "",
  },
  {
    key: "3",
    custID: "#1372",
    latestOrderDate: "03 April 2025, 09:32 PM",
    customerName: "Travis Tanner",
    deviceUse: "Counter 3",
    amount: "$64.35",
    customerStatus: "Cancelled",
  },
  {
    key: "4",
    custID: "#1298",
    latestOrderDate: "03 April 2025, 09:18 PM",
    customerName: "Jessica Kang",
    deviceUse: "Counter 2",
    amount: "$79.67",
    customerStatus: "",
  },
  {
    key: "5",
    custID: "#1264",
    latestOrderDate: "03 April 2025, 09:16 PM",
    customerName: "Monica Ngyuen",
    deviceUse: "Counter 4",
    amount: "$32.84",
    customerStatus: "Cancelled",
  },
];

export const orderData4 = [
  {
    key: "1",
    custID: "Johnny S",
    customerName: "#12345345",
    deviceUse: " 12-14-2024  09:30PM",
    amount: "Vodka Redbull",
    usePerGuest: "20",
    customerStatus: "20%",
  },
  {
    key: "2",
    custID: "Johnny S",
    customerName: "#12345345",
    deviceUse: " 12-14-2024  09:30PM",
    amount: "Vodka Redbull",
    usePerGuest: "20",
    customerStatus: "20%",
  },
  {
    key: "3",
    custID: "Johnny S",
    customerName: "#12345345",
    deviceUse: " 12-14-2024  09:30PM",
    amount: "Vodka Redbull",
    usePerGuest: "20",
    customerStatus: "20%",
  },
  {
    key: "4",
    custID: "Johnny S",
    customerName: "#12345345",
    deviceUse: " 12-14-2024  09:30PM",
    amount: "Vodka Redbull",
    usePerGuest: "20",
    customerStatus: "20%",
  },
  {
    key: "5",
    custID: "Johnny S",
    customerName: "#12345345",
    deviceUse: " 12-14-2024  09:30PM",
    amount: "Vodka Redbull",
    usePerGuest: "20",
    customerStatus: "20%",
  },
];

export const orderData5 = [
  {
    key: "1",
    custID: "Johnny Shak",
    latestOrderDate: "Johnny S",
    customerName: "200",
    deviceUse: "Pickup: 1m 45s",
    customerStatus: "Pickup: 1m 45s",
  },
  {
    key: "2",
    custID: "Johnny Shak",
    latestOrderDate: "Johnny S",
    customerName: "200",
    deviceUse: "Pickup: 1m 45s",
    customerStatus: "Pickup: 1m 45s",
  },
  {
    key: "3",
    custID: "Johnny Shak",
    latestOrderDate: "Johnny S",
    customerName: "200",
    deviceUse: "Pickup: 1m 45s",
    customerStatus: "Pickup: 1m 45s",
  },
  {
    key: "4",
    custID: "Johnny Shak Shak",
    latestOrderDate: "Johnny Shakeholic",
    customerName: "200",
    deviceUse: "Pickup: 1m 45s",
    customerStatus: "Pickup: 1m 45s",
  },
  {
    key: "5",
    custID: "Johnny ShakShakShak",
    latestOrderDate: "Johnny S",
    customerName: "200",
    deviceUse: "Pickup: 1m 45s",
    customerStatus: "Pickup: 1m 45s",
  },
];

// top seller item table data
export const mockDataSource = [
  {
    key: "1",
    drinkName: "Vodka Redbull",
    orderedCount: 1350,
    totalRevenue: "$169",
    up: "Down",
  },
  {
    key: "2",
    drinkName: "Old Fashioned",
    orderedCount: 950,
    totalRevenue: "$3124",
    up: "Up",
  },
  {
    key: "3",
    drinkName: "Lager",
    orderedCount: 732,
    totalRevenue: "$249",
    up: "Down",
  },
  {
    key: "4",
    drinkName: "Craft IPA",
    orderedCount: 428,
    totalRevenue: "$1543",
    up: "Up",
  },
  {
    key: "5",
    drinkName: "Tequila Shot",
    orderedCount: 346,
    totalRevenue: "$569",
    up: "Down",
  },
  {
    key: "6",
    drinkName: "Coors Light",
    orderedCount: 297,
    totalRevenue: "$999",
    up: "Up",
  },
  {
    key: "7",
    drinkName: "Gin & Tonic",
    orderedCount: 233,
    totalRevenue: "$119",
    up: "Down",
  },
  {
    key: "8",
    drinkName: "Red Wine",
    orderedCount: 169,
    totalRevenue: "$169",
    up: "Down",
  },
];

// guest insight service cards
export const totalGuestInsights = [
  {
    id: 1,
    name: "App Adoption Rate",
    value: "75%",
    perc: "Adoption",
  },
  {
    id: 2,
    name: "Order Frequency per User",
    value: "2.4",
    perc: "Orders/User",
  },
  {
    id: 3,
    name: "App Adoption Rate",
    value: "210",
    perc: "Redeemed",
  },
];